// GENERATED by tool/gen_peak_photos.py from assets/peaks/manifest.json – 직접 수정하지 말 것
import 'models.dart';

/// 봉우리 실사진 (자유이용 라이선스 확인분만). 없으면 일러스트로 대체.
const peakPhotos = <String, PeakPhoto>{
  'geumo': PeakPhoto(
    asset: 'assets/peaks/geumo.jpg',
    author: '한국관광공사 김지호',
    license: '공공누리 제1유형',
    licenseUrl: 'https://www.kogl.or.kr/info/licenseType1.do',
    sourceUrl: 'https://api.visitkorea.or.kr/#/hubPhotoKorea (콘텐츠ID giYoHa)',
    title: '금오산 올레길 (한국관광공사 관광사진, 콘텐츠ID giYoHa)',
  ),
  'hwangak': PeakPhoto(
    asset: 'assets/peaks/hwangak.jpg',
    author: '한국관광공사(©경상북도 공식블로그)',
    license: '공공누리 제3유형',
    licenseUrl: 'https://www.kogl.or.kr/info/licenseType3.do',
    sourceUrl: 'https://api.visitkorea.or.kr/#/hubTourSearch (관광DB 콘텐츠ID 126031 \'황악산\', 이미지 1번)',
    title: '김천_황악산 (1) — 한국관광공사 관광정보DB \'황악산\' (콘텐츠ID 126031)',
  ),
};
