"""assets/peaks/manifest.json → lib/data/peak_photos.dart 생성."""
import json, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
m = json.loads((root / 'assets/peaks/manifest.json').read_text())
import re
ids = set(re.findall(r"PeakRecord\(\s*'([^']+)'", (root / 'lib/data/gimcheon_peaks.dart').read_text()))

def q(s):
    return 'null' if s is None else "'" + str(s).replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') + "'"

rows = []
for p in m['photos']:
    if p['id'] not in ids or not (root / 'assets/peaks' / p['file']).exists():
        print('skip', p['id']); continue
    rows.append(f"  {q(p['id'])}: PeakPhoto(\n    asset: {q('assets/peaks/' + p['file'])},\n    author: {q(p['author'])},\n"
                f"    license: {q(p['license'])},\n    licenseUrl: {q(p['licenseUrl'])},\n    sourceUrl: {q(p['filePage'])},\n    title: {q(p.get('title'))},\n  ),")

out = ("// GENERATED by tool/gen_peak_photos.py from assets/peaks/manifest.json – 직접 수정하지 말 것\n"
       "import 'models.dart';\n\n/// 봉우리 실사진 (자유이용 라이선스 확인분만). 없으면 일러스트로 대체.\n"
       "const peakPhotos = <String, PeakPhoto>{\n" + '\n'.join(rows) + ("\n" if rows else "") + "};\n")
(root / 'lib/data/peak_photos.dart').write_text(out)
print(len(rows), 'photos')
